language: node_js

services:
  - docker
  - mongodb

node_js:
  - 10

install:
  - npm install typescript

script:
  - npm run lint
  - npm run build
  - npm run coverage
  - npm run codecov

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t yashkumarverma/typescript-template .
  - docker push yashkumarverma/typescript-template
  - npm i -g surge
  - surge --project ./coverage/lcov-report --domain ykv-template-cov.surge.sh
